#config/packages/svc_totp.yaml
svc_totp:

  # Default Homepage path for redirecting after actions
  home_path:            admin

  # Class to call for logging function. See documentation (capture logging) for more information
  loggingClass:         ~

  # Is "Forgot 2FA" functionality enabled?
  enableForgot2FA:      true